trinodb/charts

charts/trino/Chart.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
Since TrinoDB allows Environment Variables to be referenced in configuration files and recommends this approach for injecting secrets (https://trino.io/docs/current/security/secrets.html), this PR allows setting common environment variables for the coordinator and worker pods by adding an `envVars` value.
The `envVars` value is an array of objects in the Kubernetes Container Environment Variables format e.g.
```
envVars:
- name: S3_SECRET_KEY
valueFrom:
secretKeyRef:
name: aws-secret
key: secret-key
- name: S3_ENDPOINT
value: https://s3.site.com
```
The configuration files can then access the secret via the Environment Variable
```
hive.s3.aws-access-key=${ENV:S3_ACCESS_KEY}
```
=> Allow setting environment variables for all pods

charts/trino/Chart.yaml, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/values.yaml
query.max-total-memory-per-node was removed from trino 369. 
This PR updates the chart accordingly.   Since this chart defaults to running the `latest` trino release, its presence prevents trino from booting.
=> Remove query.max-total-memory-per-node from ConfigMap

.github/workflows/ci.yaml, .github/workflows/sync-readme.yaml
Even if linting fails we'd still want to get to know the results of
installing the chart.
=> Separate lint and test jobs and other cleanup

charts/trino/README.md, charts/trino/templates/autoscaler.yaml, charts/trino/values.yaml
Adds [horizontal pod autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) to the helm chart.
A horizontal pod autoscaler simple will simply scale the number of Trino pods based off of CPU usage.
=> Add horizontal pod autoscaler

charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/values.yaml
Similar to https://github.com/trinodb/trino/pull/11154, want to exchange-manager.properties as part of the dev setup for Helm charts.
Locally tested and deployed on EKS:
```
helm install --set additionalConfigProperties=\{"retry-policy=TASK","query.initial-hash-partitions=5","fault-tolerant-execution-target-task-input-size=10MB","fault-tolerant-execution-target-task-split-count=4","enable-dynamic-filtering=false","distributed-sort=false"\} \
--set additionalExchangeManagerProperties=\{"exchange.s3.region=us-east-1","exchange.s3.aws-access-key=accessKey","exchange.s3.aws-secret-key=secretKey"\} \
--set server.exchangeManager.baseDir="s3n://your-bucket-name"
demo ./trino-0.4.0.tgz
```
and verified cluster is running in batch mode with S3 used for spooling.
=> Add support for configuring exchange manager properties

charts/trino/README.md, charts/trino/templates/_helpers.tpl, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/templates/serviceaccount.yaml, charts/trino/values.yaml
This PR will add [Kubernetes service accounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) to the chart, along with defining some common labels in `_helpers.tpl`
=> Add Kubernetes service accounts to the chart

README.md, charts/trino/Chart.yaml, charts/trino/templates/configmap-worker.yaml
=> Fix exchange-manager.properties and bump version

charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/values.yaml
This PR will add basic configuration for [HTTPS/TLS](https://trino.io/docs/current/security/tls.html), along with `extraConfig` for additional configuration, and `secretMounts` for the secrets.
I've combined these 3 commits in this PR because they are related to each other.
This will also close #16, and removes a part of #11.
=> Add extraConfig, https, and secretMounts

charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/secret.yaml, charts/trino/values.yaml
This PR will add [`authenticationType`](https://trino.io/docs/current/security/authentication-types.html) and configs for `authenticationType = "PASSWORD"`. 
This was cherry picked from [valeriano-manassero/helm-charts](https://github.com/valeriano-manassero/helm-charts/pull/50/files) with some minor changes
=> Add support for configuring PASSWORD authentication

charts/trino/README.md, charts/trino/ci/custom-values.yaml, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values-coordinator.yaml, charts/trino/values-worker.yaml, charts/trino/values.yaml
**[Original PR was here](https://github.com/trinodb/charts/pull/19)**
This PR allows for separating jvm configs for coordinators/workers.
=> Provide different JVM configs for co-ordinator and workers

charts/trino/templates/deployment-coordinator.yaml
In version 0.7.0 of the chart if you try to deploy Trino with file based authentication, you receive this error:
```
$ helm upgrade trino trino/trino --install --version 0.7.0 --values trino.yaml --dry-run --debug
history.go:52: [debug] getting history for release trino
upgrade.go:121: [debug] preparing upgrade for trino
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[2]): unknown field "mountPath" in io.k8s.api.core.v1.Volume
helm.go:94: [debug] error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[2]): unknown field "mountPath" in io.k8s.api.core.v1.Volume
```
This PR resolves the issue.
=> Fix password auth in coordinator deployment

README.md, charts/trino/Chart.yaml, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml
This PR enables JVM options `-XX:+UnlockDiagnosticVMOptions` and `-XX:+UseAESCTRIntrinsics` to enable intrinsic support for AES CTR/GCM on ARM64. This is motivated by the SSL communication overhead observed with S3.
We observed that it improves performance of network communication with S3 a lot on graviton instances. 
It's enabled in Java 18 by default, which is already released. Therefore risk is minimal.
**Some words of explanation**
In latest Java (OpenJDK) versions the performance of AES CTR/GCM for AARCH64 was significally improved and it was backported to OpenJDK 11 (https://github.com/openjdk/jdk11u-dev/pull/410). The original OpenJDK issue can be found here: https://bugs.openjdk.java.net/browse/JDK-8267993. To use that backport we need to enable it explicitly by
enabling …
=> Add -XX:+UnlockDiagnosticVMOptions and -XX:+UseAESCTRIntrinsics

charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
This PR will allow adding [custom schemas](https://trino.io/docs/current/connector/kafka.html#table-definition-files) to be mounted in `/etc/trino/schemas`
This was cherry picked from `valeriano-manassero/helm-charts` [`#45`](https://github.com/valeriano-manassero/helm-charts/pull/45) and [`#46`](https://github.com/valeriano-manassero/helm-charts/pull/46)
=> Add support for managing Kafka table description files

charts/trino/Chart.yaml, charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
This superseeds both existing PRs:
https://github.com/trinodb/charts/pull/67
https://github.com/trinodb/charts/pull/50
As they lack splitting also `maxMemoryPerNode` which is needed to deploy coordinator on different type of node (with different amount of memory) then worker. Without it trying to deploy coordinator on smaller machine will result in error like this:
```Invalid memory configuration. The sum of max query memory per node (161061273600) and heap headroom (34359738368) cannot be larger than the available heap memory (114890375168)```
=> Split nodeSelectors configs between worker and coordinator.

charts/trino/README.md, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
Annotations are useful for integrating with a service mesh and/or cloud providers.
Also see https://github.com/trinodb/charts/pull/54.  I noticed the CLA wasn't signed yet for that PR.  I can port those changes here if needed.
=> Allow annotations and labels for the worker and coordinator pods

charts/trino/templates/configmap-coordinator.yaml
It seems discovery-server.enabled is obsolete. This commit will stop warnings about this.
=> Removed obsolete parameter discovery-server.enabled

charts/trino/README.md, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
Allow to inject envFrom values to the deployment. It is a convenient way to automatically inject all entries of a given secret/configMap as environment variables instead of selecting every entries one at a time
=> Add envFrom support to the deployment

charts/trino/templates/deployment-worker.yaml
- ~~`discovery-server.enabled` has been deprecated and `exchange.base-directory` has been renamed.~~ **EDIT**: Looks like this was merged in by #82 and b6224fb30f33694dd529a30361554e1dd64166af
- `securityContext` block was only applied to the coordinator, not to the worker.
=> Add securityContext to worker

charts/trino/README.md, charts/trino/templates/autoscaler.yaml, charts/trino/templates/configmap-catalog.yaml, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
Some organisations (like mine) require certain labels to be present on every Kubernetes resource, for example, a resource ownership label (which team owns a resource).
This PR adds `commonLabels` option that adds labels to every resource to make this use case possible.
=> Add common labels

charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/templates/ingress.yaml
This is a follow-up PR to #90
1. Ingress was added in parallel with #90 so it doesn't have the commonLabels
2. In #90 commonLabels were added to the coordinator & worker deployment, but not the pods spawned from the deployments. Fixing that
=> Add common labels to ingress and pods

charts/trino/Chart.yaml, charts/trino/README.md, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
Supersedes and closes #79 and #46 as well, see there for additional details and discussions
=> Add secretMounts for the coordinator and worker

charts/trino/Chart.yaml, charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/values.yaml
The default `jvm.config` was very outdated. It doesn't work with latest Trino, after it switched to Java 21, because `-XX:-UseBiasedLocking` is not recognized anymore.
=> Bump Trino version and fix jvm.config

charts/trino/templates/secret.yaml
Problem: if users have a solution like [Sealed Secrets](https://sealed-secrets.netlify.app/) which creates Secret objects at runtime from a Kubernetes controller, right now there's no easy way to use this instead of the default provided Secret template.
Solution: if the `auth.passwordAuth` value is not set, do not create a Secret, so that users can create their own secret containing the `passwords.db` file.
=> Only create secret if auth.passwordAuth is set

charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/secret.yaml, charts/trino/values.yaml
This allows users to change the name of the secret used for storing the password auth DB.
See also: #59 - which means you can BYO secret. When combined with this PR, you can BYO secret with any name.
=> Added auth.passwordAuthSecret value for custom passworddb secret name

charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/values.yaml
handle resource group file the same way access control is dealt with
=> handle resource group file

charts/trino/README.md, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
This change will allow the chart to take in the additional volume configurations for the coordinator and the worker.
For my use case, this is desired to authenticate the Trino Pods to a GCP project using workload identity federation.
ref) https://cloud.google.com/iam/docs/workload-identity-federation-with-kubernetes#deploy
Others seem to be interested in mounting emptyDirs etc (see Related PRs).
- https://github.com/trinodb/charts/pull/73
- https://github.com/trinodb/charts/pull/76
=> Add additionalVolumes and additionalVolumeMounts to coordinator and worker

charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/secret.yaml
Presently the chart only supports groups where password authentication is used.
This removes the limitation so that groups can be used with any authentication type. My specific use case is to enable groups with certificate authentication. However, I've also found it beneficial to be able to set groups with no authentication which has been helpful for testing.
=> Support groups without password authentication

charts/trino/README.md, charts/trino/templates/_helpers.tpl, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
We are using both a custom image registry (for caching/mirroring) and pinning the images using the image digest (instead of tag).
This pull request adds support for both custom registry and using a digest, and is backwards compatible with the current model. The actual code are inspired of the bitnami/common helm-chart.
The chart README.md file is not updated, as I assume it is regenerated in the CI/CD pipeline.
=> Added more options for specifying the container image

README.md, charts/trino/templates/autoscaler.yaml, charts/trino/templates/configmap-catalog.yaml, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/templates/ingress.yaml, charts/trino/templates/secret.yaml, charts/trino/templates/service.yaml, charts/trino/templates/serviceaccount.yaml
This PR attempts to close #114
This would be the standard way to support namespace specification.
=> Support namespace specification

charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/templates/secret.yaml, charts/trino/templates/service.yaml
=> Add missing commonLabels

charts/trino/README.md, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
- Adding Lifecycle Hook
- Added Termination Grace Period 
Those features are intended to achieve the Graceful shutdown from Trino Worker nodes.
https://trino.io/docs/current/admin/graceful-shutdown.html#admin-graceful-shutdown
With `lifecycle hooks`, when the pods receive a SIGTERM will request the API to start the `SHUTTING_DOWN` state and the `terminationGracePeriodSeconds` is for K8s waiting for this process to be concluded.
=> feat: :sparkles: Added Lifecycle Hook and Termination Grace Period 

charts/trino/templates/configmap-coordinator.yaml
add forgotten namespace when #115 was merged, @losipiuk PTAL
=> add forgotten namespace to resourceGroups manifest

.github/workflows/ci-cd.yaml, README.md, charts/trino/Chart.yaml, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml
Also, update the chart version to trigger a new release.
=> Update Trino to 448

.github/dependabot.yml, .github/workflows/ci-cd.yaml, .helmignore, .pre-commit-config.yaml, README.md, charts/trino/README.md, charts/trino/README.md.gotmpl, charts/trino/templates/autoscaler.yaml, charts/trino/templates/configmap-catalog.yaml, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/values.yaml
Use `pre-commit` so developers can use a git hook to regenerate docs.
I replaced `frigate` with `helm-docs` because frigate's pre-commit hook requires `conda` to install it. `helm-docs` run from a Docker container.
Also update all GitHub actions and enable Dependabot.
=> Replace frigate with helm-docs

charts/trino/README.md, charts/trino/values.yaml
This PR attempts to close #116
=> Support `pod.spec.containers.securityContext`  specification

charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml
Add configmap checksum for automatically roll deployments on coordinator and worker: 
- `depolyment-coordinator` : `configmap-catalog.yaml` & `configmap-coordinator.yaml`
- `deployment-worker` : `configmap-worker.yaml`
=> Add configmap checksum on deployments

charts/trino/README.md, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
Presently the chart supports only user defined secret mounts. This PR adds support for additional user defined config mounts.
I am only just getting started with trino but my use case for this at the moment is to mount a truststore for certificate authentication that is provided as a cluster wide config map.
=> Add support for additional user defined ConfigMaps

charts/trino/README.md, charts/trino/templates/service.yaml, charts/trino/values.yaml, test-values.yaml
Enables the user to add annotations for the service resource so it can be integrated with load balancers and others.
This is a similar PR to https://github.com/trinodb/charts/pull/54 and aims to resolve the long-standing issue https://github.com/trinodb/trino/issues/13085, however as the PR hasn't had any progress in almost a year, trying to push through separately.
=> Support service annotations

charts/trino/templates/_helpers.tpl, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/secret.yaml
=> Template the password secret name

charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml
Use the health check script as the readiness probe, because it also checks the response of the `/v1/info` endpoint to make sure the server actually finished starting up. This only makes sense for the readiness probe, so keep the liveness probe as-is.
This should fix the flaky test issues observed in the workflow runs: https://github.com/trinodb/charts/actions/workflows/ci-cd.yaml?query=is%3Afailure
=> Use a better readiness probe

charts/trino/templates/NOTES.txt, charts/trino/templates/_helpers.tpl, charts/trino/templates/autoscaler.yaml, charts/trino/templates/configmap-catalog.yaml, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/templates/ingress.yaml, charts/trino/templates/secret.yaml, charts/trino/templates/service.yaml, charts/trino/templates/tests/test-connection.yaml, test.sh
Use standard Helm labels, following https://helm.sh/docs/chart_best_practices/labels/#standard-labels. Use labels on all resources, so the chart can be uninstalled correctly.
Additionally, print logs after failed installs. Because `ct install` calls `helm test` without `--logs`, always pass `--skip-clean-up`, and get the logs and cleanup manually after a failure.
=> Use standard labels

.github/workflows/ci-cd.yaml, charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml, test.sh
Replaces #163 and #170 
Closes #159
=> Enabled overrides for worker and coordinator configmap resources

.github/workflows/ci-cd.yaml
I removed this in #175 because the comment was misleading, it might be required for releases.
=> Fetch full history when doing releases

charts/trino/Chart.yaml, charts/trino/README.md, charts/trino/templates/ingress.yaml, test-values.yaml
Upgrading to 0.23.0, I get this error 
```
Error: template: trino/templates/ingress.yaml:33:25: executing "trino/templates/ingress.yaml" at <include "trino.fullname" .>: error calling include: template: trino/templates/_helpers.tpl:15:14: executing "trino.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
helm.go:84: [debug] template: trino/templates/ingress.yaml:33:25: executing "trino/templates/ingress.yaml" at <include "trino.fullname" .>: error calling include: template: trino/templates/_helpers.tpl:15:14: executing "trino.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
```
This PR aims to fix nil pointer evaluating interface, by using $, which references the global scope in order to access the …
=> Fix nil pointer evaluating interface

README.md, charts/trino/Chart.yaml, charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-jmx-exporter.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/service.yaml, charts/trino/templates/servicemonitor.yaml, charts/trino/templates/tests/test-connection.yaml, charts/trino/templates/tests/test-jmx.yaml, charts/trino/values.yaml, test-values.yaml, test.sh
Replaces #182, with some review comments applied and with properly squashed commits.
Replaces #140 and replaces #135.
=> Add support for jmx metrics and prometheus exporter

test.sh
When running tests except `complete_values`, when the Prometheus Operator is not being installed, there are no extra CRDs to remove, and the delete command was failing. Check explicitly if there's anything to remove.
=> Fix deleting CRDs at the end of tests

README.md, charts/trino/Chart.yaml, charts/trino/README.md, charts/trino/templates/tests/test-jmx.yaml
Update Trino to 450, which is the latest available now.
=> Update app and chart versions

charts/trino/README.md, charts/trino/templates/service.yaml, charts/trino/values.yaml, test-values.yaml
Hello.
This PR is to be able to customize the NodePort in the Trino service.
I adjusted it due to the issue https://github.com/trinodb/charts/issues/203.
=> feat: added ability to define the nodePort in the trino service

charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/values.yaml, test-access-control-properties-values.yaml, test.sh
This PR is the conclusion of [this PR](https://github.com/trinodb/charts/pull/88).
Adds the ability to use custom access control (eg. Open Policy Agent).
=> Allow using custom accessControl (eg. OPA)

charts/trino/templates/configmap-access-control.yaml, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/deployment-coordinator.yaml
mv roles configmap to another file, bacause we don't need to restart coordinator after edit roles
=> mv roles configmap to another file

charts/trino/templates/configmap-coordinator.yaml
As for now, one you've set your auth type to `"PASSWORD"` via `Values.server.config.authenticationType`, you are forced to use a[ specific conf file](https://github.com/trinodb/charts/blob/main/charts/trino/templates/configmap-coordinator.yaml#L125) set for [password file auth](https://trino.io/docs/current/security/password-file.html).
This implementation restricts auth configurations in the following ways:
1. It restricts the usage of configurations specific to that auth implementation (e.g., we cannot configure `file.auth-token-cache.max-size`).
2. Even worse, it does not allow configuring LDAP properties, which should also be enabled by the `"PASSWORD"` auth type.
This PR suggests a  small fix to address these scenarios.
=> Support custom password auth properties file

charts/trino/README.md, charts/trino/templates/deployment-coordinator.yaml, charts/trino/values.yaml
Allows to set resources for the JMX Exporter container.
Resolves #202 for K8s clusters with strict resource quota policies.
=> Allow to set resources for the JMX Exporter container

charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/values.yaml, test-exchange-manager-values.yaml, test.sh
Currently the exchange manager properties file is always created via Helm chart although this is considered as an optional configuration in Trino. In this PR I made its creation conditional according to whether or not the `.Values.server.exchangeManager` was set.
I also removed the condition in its properties file, that links between `exchamge-manager.name=filesystem` to  `exchange.base-directories` existence, as they are not dependent (you can see [here](https://trino.io/docs/current/admin/fault-tolerant-execution.html#id1) that this configuration supports also `hdfs` as the value of `exchamge-manager.name`).
**Note:**
1. I was thinking of uniting `.Values.server.exchangeManager` and `.Values.server.additionalExchangeManagerProperties` as it seems more convenient to have all the exchange …
=> Make exchange manager conditional

charts/trino/README.md, charts/trino/templates/configmap-jmx-exporter.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/values.yaml
I moved the JMX Exporter container port to correct container (previously located on the coordinator container), with a minor.
Also, the property `.Values.jmx.exporter.configProperties` was declared as a list which was incorrect. I converted it to a templated multiline string.
I also updated the minimal JMX configuration example in the default value of `.Values.jmx.exporter.configProperties`.
Fixes #221
=> Fix JMX Exporter container port spec

charts/trino/README.md, charts/trino/templates/configmap-catalog.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
I moved the default `tpch` and `tpcds` catalogs from the related configmap into a unified `catalogs` configuration where users will be able to remove them if neccessary.
If no catalogs are provided, the related configmap will not be created/mounted. 
This `additionalCatalogs` property has now been deprecated in favor of the newly introduced `catalogs`.
Fixes: #210
=> Optional catalogs and related configmap

charts/trino/README.md, charts/trino/values.yaml
closes: https://github.com/trinodb/charts/issues/229
=> remove `.Values.server.config.http` section from chart

charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-jmx-exporter.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/templates/service-coordinator.yaml, charts/trino/templates/service-worker.yaml, charts/trino/templates/servicemonitor-coordinator.yaml, charts/trino/templates/servicemonitor-worker.yaml, charts/trino/templates/tests/test-jmx.yaml, charts/trino/values.yaml, test-values.yaml, test.sh
=> Add option to enable JMX exporter on workers

charts/trino/README.md, charts/trino/templates/autoscaler.yaml, charts/trino/values.yaml, test-values.yaml
Hello!
This PR aims to enable the possibility of using memory resource in the HPA. I noticed that there is an open PR (https://github.com/trinodb/charts/pull/219) regarding this, but it has been inactive for a month, and this is a feature I really need.
A new variable has been created in the values (targetMemoryUtilizationPercentage), with a default value of 80. In the HPA manifest, I added a conditional check to see if a value is set for this variable, allowing the assignment of an empty value ("") to one of them to not use the metric. I also included this condition for targetCPUUtilizationPercentage (since someone might not want to scale based on CPU).
=> Allow autoscaling by memory utilization

README.md, charts/trino/Chart.yaml, charts/trino/README.md, charts/trino/values.yaml
Prepare to release the next version
=> Update Trino and chart version

charts/trino/README.md, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml, test-values.yaml
Reference PR: #236 
Adding deployment spec values for `coordinator` deployment and `worker` deployment:
```
- progressDeadlineSeconds
- revisionHistoryLimit
- strategy
```
This is needed for us in case of an update of Trino Cluster that requires the deployment to bring pods up and down.
=> Add deployment spec properties to coordinator and worker

charts/trino/README.md, charts/trino/templates/service-coordinator.yaml, charts/trino/values.yaml, test-values.yaml
When deploying on Kubernetes I was faced with additionalExposedPorts nodePorts that kept changing after each deploy due to the nodePort not being specified in the Helm chart, as explained here https://trinodb.slack.com/archives/CGB0QHWSW/p1727943085442609?thread_ts=1722396654.245879&cid=CGB0QHWSW
The purpose of this pull request is to allow something like:
```
additionalExposedPorts:
https:
servicePort: 8443
name: https
port: 8443
nodePort: 30443
protocol: TCP
```
not only for https but also for other services.
=> Allow setting nodePort in .Values.coordinator.additionalExposedPorts

.github/release.yml
PR labels will allow categorizing changes in release notes, especially highlighting breaking changes.
=> Use PR labels when generating release notes

.github/workflows/ci-cd.yaml
The gateway chart doesn't have any README yet, so don't try to publish it, only add the chart to the index.
=> Release both trino and trino-gateway charts

charts/trino/README.md, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml, test-values.yaml
=> Support setting annotations in deployments

charts/trino/README.md, charts/trino/templates/_helpers.tpl, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/secret.yaml, charts/trino/values.yaml
Hello!
I'm not very experienced with Trino configuration, but I do have a bit more experience with Helm charts.
The main question in this PR is determining the correct place to change the file.password-file and file.group-file configurations.
I placed them in a separate folder to keep automatic updates when k8s secrets are updated.
This approach contrasts with using subPath, which does not support automatic file updates within pod volumes.
=> add_separate_group.db_secret

charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/tests/test-connection.yaml, charts/trino/values.yaml, test-resource-groups-properties-values.yaml, test-values.yaml, test.sh
This PR enhances the Trino Helm chart by adding support for the Database resource group manager. Previously, only file-based configurations using ConfigMap were supported.
Additionally, the implementation is closely modeled after the existing accessControl pattern in the chart, ensuring consistency in the configuration approach.
In the process of implementing this feature, we considered deploying the MySQL container in the same namespace as Trino to streamline configuration. However, the MySQL service endpoint URL includes the namespace, making it challenging to set a dynamic reference. To maintain stability and avoid complex configurations, we fixed the MySQL namespace as mysql, ultimately deciding against further attempts at a flexible namespace solution for this PR.
=> Add support for Database resource group manager

README.md
Adjusting to the presence of the Trino Gateway chart basically.
Related to https://github.com/trinodb/trino-gateway/pull/558
Also fyi @willmostly
=> Improve readme content

charts/gateway/Chart.yaml, charts/gateway/README.md
For Trino Gateway 13
Also @willmostly
=> Release Trino Gateway chart 1.13.0

charts/trino/README.md, charts/trino/templates/servicemonitor-coordinator.yaml, charts/trino/templates/servicemonitor-worker.yaml, charts/trino/values.yaml
This feature enables users to override the Service Monitor API version if they are using Azure managed prometheus which uses `azmonitoring.coreos.com/v1` instead of the default `monitoring.coreos.com/v1`.
=> Add service monitor API version override

charts/gateway/README.md, charts/gateway/templates/service.yaml, charts/gateway/values.yaml
- Introduced functionality to allow specifying annotations for Trino Gateway services.
- Ensures compatibility with Kubernetes custom annotations for enhanced service configurations.
- Updated relevant templates and documentation to reflect the changes.
This feature enables users to add annotations for service monitoring, ingress, or other Kubernetes integrations.
=> Add service annotations support to Trino Gateway Chart

charts/gateway/README.md, charts/gateway/templates/deployment.yaml, charts/gateway/templates/secrets.yaml, charts/gateway/values.yaml, tests/gateway/test-values-with-env.yaml, tests/gateway/test.sh
Add `envFrom` to allow providing environment variables from Secrets, and remove usage of the Helm `lookup` function for merging Secrets into the configuration. 
This removes the custom checksum calculation as well. The checksum had included the optional configuration secrets, causing pod restarts whether configuration was updated through the chart or through a secret. Since this required retrieving Secrets from the target cluster through the Helm `lookup` function, it caused the chart to be incompatible with release pipelines in which a manifest is generated in an environment that does not have access to the target cluster.
=> Add envFrom and remove lookup

.gitignore, charts/gateway/README.md, charts/gateway/templates/NOTES.txt, charts/gateway/templates/deployment.yaml, charts/gateway/templates/ingress.yaml, charts/gateway/templates/service.yaml, charts/gateway/templates/tests/test-connection.yaml, charts/gateway/values.yaml, tests/gateway/test-https.yaml, tests/gateway/test-nodeport.yaml, tests/gateway/test.sh
Kubernetes supports several types of services. This change passes through arbitrary keys under `service.spec`, which allows specifying type-specific keys such as `nodePort`. The `port` and `targetPort` are autoconfigured to match the port specified in the gateway `http-server` configuration, and the selector is autoconfigured to match the deployment.
Suggested release note:
* Set custom service attributes.  **Breaking change**: the `service` node no longer uses `type` and `port` as a subfields. Define the `service.spec` instead.
=> Pass through service spec values

charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/values.yaml
This change will allow using list syntax of exchangeManager base-directories which is more common and understandable with Helm charts.
Trino allows specifying multiple spooling targets for exchageManager separated by comma when using main cloud providers or any S3 compatible protocol (example: s3://bucket1,s3://bucket2,s3://bucket3). With current trinodb/charts we have to specify them within values as a single line for baseDir:
```
server:
exchangeManager:
name: "filesystem"
baseDir: "s3://exchange-spooling-bucket-1,s3://exchange-spooling-bucket-2"
```
Which translates to:
```
exchange-manager.properties: |
exchange-manager.name=filesystem
exchange.base-directories=s3://exchange-spooling-bucket-1,s3://exchange-spooling-bucket-2
```
This change allows a more clean listing within values: …
=> Allow list syntax for exchangeManager baseDir targets

charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/templates/ingress.yaml, charts/trino/templates/tests/test-connection.yaml, tests/trino/test-values.yaml, tests/trino/test.sh
The current chart implementation requires static secret and configmap names to be provided in various mount-related values (`envFrom`, `additionalVolumes`, `secretMounts`, etc.).
This creates a challenge when the Trino chart is deployed as part of a parent  chart, with multiple deployments in the same namespace.
Similar to the Trino chart (which uses `{{ template "trino.fullname" . }}-` for unique resource names), the parent chart resource names are often rendered according to release-specific values, so the static naming requirement for these mounts of resources external in the Trino chart creates a limitation in such scenarios.
[Similar PRs](https://github.com/trinodb/charts/pull/283) have been raised in the past, including [one I previously opened …
=> Template external secrets configs injection

charts/gateway/README.md, charts/gateway/values.yaml, tests/gateway/test-values-with-env.yaml, tests/gateway/test-values.yaml
Remove `HaGatewayProviderModule`, `ActiveClusterMonitor`, `ClusterStateListenerModule`,
and `ClusterStatsMonitorModule` from Trino Gateway config file.
Gateway loads fundamental modules by default after https://github.com/trinodb/trino-gateway/pull/597.
This PR should be merged together with Trino Gateway 14 upgrade.
=> Remove deprecated settings from gateway config

README.md, charts/gateway/Chart.yaml, charts/gateway/README.md
In preparation for the release managed at https://github.com/trinodb/trino-gateway/pull/589
Must cut Trino Gateway release and merge https://github.com/trinodb/charts/pull/296 before this PR is merged
=> Release Trino Gateway chart 1.14.0

charts/gateway/templates/tests/test-connection.yaml
The DB is now initialized by Flyway
=> Remove DB initialization from tests

README.md, charts/gateway/Chart.yaml, charts/gateway/README.md, charts/gateway/templates/deployment.yaml, charts/gateway/values.yaml, tests/gateway/test-https.yaml
**Merge after upgrade to Trino Gateway 15**
Update config path path for gateway.
Changes:
* `/etc/gateway/config.yaml` to `/etc/trino-gateway/config.yaml`
* `/usr/lib/trino` -> `/usr/lib/trino-gateway`
Ref:
* https://github.com/trinodb/trino-gateway/pull/623
* https://github.com/trinodb/trino-gateway/pull/628
=> Update config path path for Trino Gateway and release chart

charts/trino/README.md, charts/trino/templates/configmap-coordinator.yaml, charts/trino/templates/configmap-worker.yaml, charts/trino/values.yaml, tests/trino/test-values.yaml
Support templating of the environment name.
This has two advantages:
- Avoid duplication of the environment name between trino and other parts of the deployment. _YAML anchors would still add substantial boilerplate_.
- Allows the existing environment name to be modified to meet trino naming requirements (e.g replacing dash with underscore).
For example...
values.yaml
```
trino:
server:
node:
environment: "{{ .Values.global.env | replace \"-\" \"_\" }}"
```
values-dev-region-a.yaml
```
global:
env: "dev-region-a"
```
=> Enable templating of environment name

charts/trino/templates/NOTES.txt
This is really minor change to add the namespace to the kubectl port-forward command output after deploying the chart.
The change already exists in the gateway chart, so just adds the same for trino.
=> Include namespace in port-forward command

charts/gateway/templates/deployment.yaml, charts/gateway/templates/secrets.yaml
Ensure the secret and volume names dynamically use the chart's full name instead of a hardcoded value, aligning with Helm best practices and preventing naming conflicts in multi-instance deployments.
- Replace static references (`trino-gateway-configuration`) with templated Helm function (`{{ include "trino-gateway.fullname" . }}-configuration`).
- Update secret definition in `secrets.yaml`.
- Update volume mounts and secret references in `deployment.yaml`.
=> Fix secret naming consistency

charts/trino/README.md, charts/trino/templates/service-worker.yaml, charts/trino/values.yaml, tests/trino/test-values.yaml
Currently additionaly exposed ports are not added to trino  worker service. This change will add them.
=> Use worker's additional exposed ports in the worker service

charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/templates/ingress.yaml, charts/trino/templates/service-coordinator.yaml, tests/trino/test-values.yaml
The changes below are a subset of the changes seen in #300 but the PR hasn't seen activity in over a month so I thought it might make sense to create this small PR. The changes in this PR are also independent of the other changes proposed by #300 to support internal TLS.
=> Don't require adding the https port in `additionalExposedPorts` when https is enabled

charts/gateway/templates/tests/test-connection.yaml
NodePort test for Trino Gateway was kind of flaky, so I did the following to make it more reliable:
* changed docker image to `alpine/curl` so we can avoid installing `curl`;
* increased retries to 5, connection timeout to 10s, retry delay to 10s since the NodePort service is not immediately available in Kind;
* refactored the general test logic for readability.
=> Refactor Trino Gateway test-connection

charts/trino/README.md, charts/trino/values.yaml
A small fix, however, took me a while to figure out those spaces should not be there 🥲
=> Remove extra spaces in comments

charts/gateway/README.md, charts/gateway/templates/deployment.yaml, charts/gateway/values.yaml
Allow [topologySpreadConstraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) to be configurable for the Trino gateway deployment. 
A common usecase for this would be ensuring that pods are available in multiple AZ to make the Trino gateway deployment more resilient to single AZ failures.
=> Add configurable topologySpreadConstraints for Trino gateway deployment

.github/workflows/ci-cd.yaml
This pull request updates the CI/CD workflow to conditionally run tests (https://github.com/trinodb/charts/issues/345). The kind cluster setup and tests will be skipped if there are no changes detected in pull requests or push events.
**Trino Tests**:  detect changes in 
- `charts/trino/**`, 
- `tests/trino/**`, 
- `.helmignore` 
- `.github/**`
- `.gitignore`
**Gateway Tests**:  detect changes in 
- `charts/gateway/**`, 
- `tests/gateway/**`, 
- `.helmignore` 
- `.github/**`
- `.gitignore`
=> Run CI tests only if Trino and Gateway file change

charts/gateway/templates/secrets.yaml
Made minor adjustments to the `trino-gateway-configuration` Secret, fixed indentation & added metadata labels to enhance consistency & readability.
=> Add labels to the trino-gateway-configuration secret

charts/trino/README.md, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml, tests/trino/test-values.yaml
This PR adds support for `topologySpreadConstraints` to the worker deployment. This allows users to improve cluster resilience and resource balancing by controlling how worker pods are spread across nodes and availability zones.
The feature is enabled by setting the `worker.topologySpreadConstraints` value in `values.yaml`. Tests have been added to verify the implementation.
**Example `values.yaml` configuration:**
```yaml
worker:
topologySpreadConstraints:
- maxSkew: 1
topologyKey: "kubernetes.io/hostname"
whenUnsatisfiable: "ScheduleAnyway"
labelSelector:
matchLabels:
app.kubernetes.io/name: trino
app.kubernetes.io/component: worker
```
=> Add topologySpreadConstraints for workers

charts/trino/templates/configmap-coordinator.yaml
Although the chart support passing external secret as group db via `groupAuthSecret` besides adding directly to `groups` under `auth` section , there is some typos and logic missing causing `group-provider.properties` not being created, leads to the rendered `group.db` not being injected into the cluster
=> Fix group auth secret not injected correctly

charts/trino/README.md, charts/trino/templates/deployment-coordinator.yaml, charts/trino/templates/deployment-worker.yaml, charts/trino/values.yaml
This PR updates the `trino/` Helm chart so that `coordinator/worker.deployment.strategy` is empty by default instead of pre-filled with a `RollingUpdate` default K8s configurations.
Currently, the chart always renders a `.spec.strategy.rollingUpdate` block in the deployment manifest, even when users want to use `.spec.strategy.type==Recreate`. This leads to confusing output, especially when using wrapper charts (in which `rollingUpdate` is impossible to override) or custom values files (which make you set `rollingUpdate` to `null` while using `Recreate` type).
K8s fails to create the deployment when `.spec.strategy.rollingUpdate` appears in conjunction with `.spec.strategy.type==Recreate`.
The following changes eliminate the need for workarounds like `null` to override the `rollingUpdate` …
=> Remove default deployment strategy values
