charts/trino/README.md
charts/trino/templates/deployment-coordinator.yaml
charts/trino/templates/deployment-worker.yaml
charts/trino/values.yaml

Based off @valeriano-manassero contributions

Add support for init containers for worker and coordinator

---

charts/trino/README.md
charts/trino/templates/deployment-coordinator.yaml
charts/trino/templates/deployment-worker.yaml
charts/trino/values.yaml

Replace hardcoded imagePullSecrets "registry-credentials" to values 😄

feat: customizable imagePullSecrets

---

charts/trino/README.md
charts/trino/templates/configmap-coordinator.yaml
charts/trino/templates/deployment-coordinator.yaml
charts/trino/values.yaml

This PR adds the access control template cherry picked from @valeriano-manassero's chart.

Add support for file-based system-level access control

---

charts/trino/Chart.yaml
charts/trino/README.md
charts/trino/values.yaml

This has no real effect since the tag used is "latest" but 375 is very wrong... 420 is getting released today.

Set appVersion and tag to 423

---

charts/trino/templates/configmap-coordinator.yaml
charts/trino/templates/deployment-coordinator.yaml
charts/trino/templates/secret.yaml
charts/trino/values.yaml

Add users' groups for group file provider: https://trino.io/docs/current/security/group-file.html#file-format

Add support for users groups

---

README.md

Update version in README to latest

---

charts/trino/README.md
charts/trino/templates/autoscaler.yaml
charts/trino/values.yaml

add hpa behavior & bump autoscaling api to v2

add hpa behavior

---

charts/trino/templates/configmap-coordinator.yaml
charts/trino/templates/deployment-coordinator.yaml
charts/trino/templates/secret.yaml

rebased version of [PR-86](https://github.com/trinodb/charts/pull/86)

make password work with other auth types

---

README.md
charts/trino/Chart.yaml

I think we can cut a new release now and then another one once the currently active PRs are in.. 
I also think we should update to 442 once thats out.

Change version to 0.19.0

---

charts/trino/templates/deployment-coordinator.yaml

See discussion after merge in #108

Fix breakage from #108 - password.db is needed when passwordAuthSecret is set

---

charts/trino/README.md
charts/trino/values.yaml

Fix defaults and document additional properties sections

---

README.md
charts/trino/Chart.yaml
charts/trino/README.md

Update Trino to 449 and bump the chart version

Update Trino and chart version

---

charts/trino/README.md
charts/trino/values.yaml

We have comments on other sections but not on this configuration. 
Adding an example of how to use this `additionalExchangeManagerProperties`

Add comments for Additional Exchange Manager Properties

---

README.md
charts/trino/Chart.yaml
charts/trino/README.md

Prepare to release the next version.

Update Trino and the chart version

---

.github/workflows/ci-cd.yaml
.helmignore
README.md
charts/gateway/Chart.yaml
charts/gateway/README.md
charts/gateway/templates/NOTES.txt
charts/gateway/templates/_helpers.tpl
charts/gateway/templates/deployment.yaml
charts/gateway/templates/hpa.yaml
charts/gateway/templates/ingress.yaml
charts/gateway/templates/secrets.yaml
charts/gateway/templates/service.yaml
charts/gateway/templates/serviceaccount.yaml
charts/gateway/templates/tests/test-connection.yaml
charts/gateway/values.yaml
test.sh

Copied the chart from https://github.com/trinodb/trino-gateway/tree/main/helm/trino-gateway (with all previous authors attributed), added tests, fixed up the readme, etc.
I had to revert to Trino Gateway 11, since 12 is not published yet.

Add the Gateway chart

---

README.md

I looked at the rendered output at https://trinodb.github.io/charts/ and thought this needs some improvements to make the links clearer.

Improve overview docs

---

.github/workflows/ci-cd.yaml
README.md
charts/trino/Chart.yaml
charts/trino/README.md

Update Trino to 467 and prepare for the next release of the chart.

Prepare for next release of the Trino chart

---

README.md
charts/gateway/Chart.yaml
charts/gateway/README.md
charts/gateway/templates/ingress.yaml
tests/gateway/test-https.yaml
tests/gateway/test-values.yaml

Fix a regression introduced in #271 and enable ingress in tests to make sure we catch issues like this.

Fix the Gateway ingress resource

---

charts/gateway/templates/deployment.yaml

Adjustment to https://github.com/trinodb/trino-gateway/pull/595 which ships in Trino Gateway 14
Ideally included for Trino Gateway 14 upgrade in https://github.com/trinodb/charts/pull/289
Fyi @oneonestar and @willmostly

Use health endpoints of Trino Gateway

---

charts/gateway/README.md
charts/gateway/templates/deployment.yaml
charts/gateway/values.yaml
tests/gateway/test-values.yaml

Support for initContainers for gateway chart

initContainers for gateway

---

charts/gateway/templates/NOTES.txt

Fix rendering notes for load-balancer service

---

charts/gateway/README.md
charts/gateway/templates/deployment.yaml
charts/gateway/values.yaml

volumes and volumeMounts should be lists and having tpl would be a nice addition.

volumes and volumeMounts as lists with tpl

---

charts/trino/README.md
charts/trino/values.yaml

with example on how do disable automatic Pod restart on configuration changes.
Closes #259

Add annotations documentation for coordinator and worker Trino Pods

---

charts/trino/templates/deployment-worker.yaml
charts/trino/templates/tests/test-graceful-shutdown.yaml
tests/trino/test-graceful-shutdown-values.yaml

Enhance graceful shutdown handling in worker deployment
